#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

picom &

bash ~/.config/polybar/launch.sh &

bspc monitor -d ter web dsc music code oth1 oth2 oth3 oth4 oth5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a VSCodium desktop="^5"
bspc rule -a "YouTube Music" desktop="^4"
bspc rule -a discord desktop="^3"
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
flameshot